# action.yml
name: 'Provenance Action'
description: 'Action to test Provenance and Smart Contracts'
inputs:
  github_token:
    description: 'Github token from the workflow'
    required: true
  provenance_version:  # version of Provenance
    description: 'Version of Provenance to test, either a release or a branch'
    required: true
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: false
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
#outputs:
#  store_code_proposal:
#    description: 'The store code governance proposal in json format'
#    value: ${{ steps.smart-contract-action.outputs.store_code_proposal }}
#  instantiate_code_proposal:
#    description: 'The instantiate code governance proposal in json format'
#    value: ${{ steps.smart-contract-action.outputs.instantiate_code_proposal }}
#  migrate_code_proposal:
#    description: 'The migrate code governance proposal in json format'
#    value: ${{ steps.smart-contract-action.outputs.migrate_code_proposal }}
runs:
  using: composite
  steps:
    - name: download provenance release
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.provenance_version }}
        repo: provenance-io/provenance
        workflow: release.yml
        workflow_conclusion: success
        name: linux-zip
    - name: run smart contract action
      id: smart-contract-action
      uses: ./smart-contract-action
      with:
        test_script: ${{ inputs.test_script }}
        generate_proposals: ${{ inputs.generate_proposals }}
    - name: attach artifacts
      uses: actions/upload-artifact@v3
      with:
        name: proposals
        path: |
          ${{ steps.smart-contract-action.outputs.store_code_proposal }}
          ${{ steps.smart-contract-action.outputs.instantiate_code_proposal }}
          ${{ steps.smart-contract-action.outputs.migrate_code_proposal }}
