# action.yml
name: 'Provenance Action'
description: 'Action to test Provenance and Smart Contracts'
inputs:
  provenance_version:  # version of Provenance
    description: 'Version of Provenance to test'
    required: false
  provenance_branch:
    description: 'Branch of Provenance to test'
    required: false
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: false
runs:
  using: composite
  steps:
    - name: validate provenance version
      uses: actions/github-script@v3
      if: ${{ inputs.provenance_version == '' && inputs.test_script == '' }}
      with:
        script: |
          core.setFailed('`provenance_version` or `provenance_pr` must be set')
    - name: run smart contract test
      uses: ./test
      with:
        test_script: ${{ inputs.test_script }}
