# action.yml
name: 'Smart Contract Action'
description: 'Action to test Smart Contracts with Provenance'
inputs:
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: true
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
outputs:
  store_code_proposal:
    description: 'The store code governance proposal in json format'
  instantiate_code_proposal:
    description: 'The instantiate code governance proposal in json format'
  migrate_code_proposal:
    description: 'The migrate code governance proposal in json format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test_script }}
    - ${{ inputs.generate_proposals }}
