# action.yml
name: 'Smart Contract Action'
description: 'Action to test Smart Contracts with Provenance'
inputs:
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: true
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
  wasm_path:
    description: 'Path to the smart contract wasm'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test_script }}
    - ${{ inputs.generate_proposals }}
    - ${{ inputs.wasm_path }}
