name: Test
on:
  pull_request:
jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  test_with_provenance_release:
    runs-on: ubuntu-latest
    name: Test Tutorial Smart Contract
    steps:
      - name: Smart Contract Test setup
        uses: ./
        with:
          provenance_version: "v1.8.0"
          test_script: "./scripts/test.sh"

  
  test_with_provenance_pr:
    runs-on: ubuntu-latest
    name: Test Tutorial Smart Contract
    steps:
      - name: Smart Contract Test setup
        uses: ./
        with:
          provenance_version: "v1.8.0"
          test_script: "./scripts/test.sh"